mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("quotes.urls")),
    path("users/", include("users.urls", namespace='users')),
]

mysite/quotes/urls.py
from django.urls import path

from . import views

app_name = "quotes"
urlpatterns = [
    path("", views.main, name="root"),
    path("<int:page>", views.main, name="root_paginate"),
    path('author/<int:_id>/', views.author_about, name='author_about'),
    path('add_quote/', views.add_quote, name='add_quote'),
    path('add_author/', views.add_author, name='add_author'),

]

mysite/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from . import views
from .forms import LoginForm
from .views import RegisterView

app_name = "app_users"

urlpatterns = [
    path('signin/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(
        template_name='users/login.html',
        authentication_form=LoginForm,
        redirect_authenticated_user=True
    ), name='login'),
    path('logout/', LogoutView.as_view(
            template_name='users/logout.html',
        ), name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),

]

mysite/quotes/models.py
from django.db import models


# Create your models here.

class Author(models.Model):
    fullname = models.CharField(max_length=50, unique=True)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=100)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.fullname}'

class Tag(models.Model):
    tag = models.CharField(max_length=50, unique=True, null=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.tag}'


class Quote(models.Model):
    quote = models.TextField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    tags = models.ManyToManyField(Tag)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.quote}'

mysite/users/models.py
from django.db import models


# Create your models here.

mysite/quotes/forms.py
from django.forms import ModelForm, CharField, TextInput, ModelMultipleChoiceField, ModelChoiceField, Select, \
    SelectMultiple
from .models import Quote, Author, Tag


class QuoteForm(ModelForm):
    quote = CharField(min_length=5, required=True, widget=TextInput())
    author = ModelChoiceField(queryset=Author.objects.all().order_by("fullname"), widget=Select())
    tags = ModelMultipleChoiceField(queryset=Tag.objects.all().order_by("tag"), required=True,
                                    widget=SelectMultiple())

    class Meta:
        model = Quote
        fields = ['quote', 'author', 'tags']


class AuthorForm(ModelForm):
    fullname = CharField(max_length=50, widget=TextInput())
    born_date = CharField(max_length=50, widget=TextInput())
    born_location = CharField(max_length=150, widget=TextInput())
    description = CharField(widget=TextInput())

    class Meta:
        model = Author
        fields = ["fullname", "born_date", "born_location", "description"]


class TagForm(ModelForm):
    tag = CharField(max_length=50, widget=TextInput())

    class Meta:
        model = Tag
        fields = ["tag"]

mysite/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=50, required=True, widget=forms.TextInput({'class': 'form-control'}))
    email = forms.CharField(max_length=50, required=True, widget=forms.EmailInput({'class': 'form-control'}))
    password1 = forms.CharField(max_length=20, min_length=5, required=True,
                                widget=forms.PasswordInput({'class': 'form-control'}))
    password2 = forms.CharField(max_length=20, min_length=5, required=True,
                                widget=forms.PasswordInput({'class': 'form-control'}))

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]


class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=50, required=True, widget=forms.TextInput({'class': 'form-control'}))
    password = forms.CharField(max_length=20, min_length=5, required=True,
                               widget=forms.PasswordInput({'class': 'form-control'}))

    class Meta:
        model = User
        fields = ["username", "password"]

mysite/quotes/views.py
from django.db.models import Count
from django.shortcuts import render, redirect
from django.core.paginator import Paginator


from .utils import get_mongodb
from .models import Author, Quote, Tag
from .forms import QuoteForm, AuthorForm, TagForm


def main(request, page=1):
    db = get_mongodb()
    quotes = db.quote.find()
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    return render(request, "quotes/index.html", context={'quotes': quotes_on_page})

def author_about(request, _id):
    print(_id)
    author = Author.objects.get(pk=_id)
    print(author.fullname, type(author))

    return render(request, 'quotes/author.html', context={'author': author})

def add_quote(request):
    if request.method == "POST":
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save()
            return redirect(to="quotes:root")
        else:
            return render(request, "quotes/add_quote.html",
                          context={'form': QuoteForm(), "message": "Form not valid"})
    return render(request, "quotes/add_quote.html", context={'form': QuoteForm()})

def add_author(request):
    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            new_quote = form.save()
            return redirect(to="quotes:root")
        else:
            return render(request, "quotes/add_author.html",
                          context={'form': AuthorForm(), "message": "Form not valid"})
    return render(request, "quotes/add_author.html", context={'form': AuthorForm()})

mysite/users/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from .forms import RegisterForm


class RegisterView(View):
    form_class = RegisterForm
    template_name = 'users/signin.html'

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect(to='quotes:root')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        return render(request, self.template_name, {'form': self.form_class})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            messages.success(request, f"Wellcome, {username}! Your account has been created.")
            return redirect(to="users:login")
        return render(request, self.template_name, {'form': form})


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'users/password_reset_subject.txt'

mysite/quotes/templates/quotes/add_author.html
{% extends "quotes/base.html" %}

{% block content %}
<div class="container">
    <h2 class="titleForm">Add Author:</h2>
    <br>
    <form class="col-sm-8" method="POST" action="{% url 'quotes:add_author' %}">
        {% csrf_token %}
        <div class="form-group mb-3">
            <label for="id_fullname">Author:</label>
            {{ form.fullname }}
            <span class="error">{{ form.errors.fullname }}</span>
        </div>
        <div class="form-group mb-3">
            <label for="id_born_date">Born Date:</label>
            {{ form.born_date }}
            <span class="error">{{ form.errors.born_date }}</span>
        </div>
        <div class="form-group mb-3">
            <label for="id_born_location">Born Location:</label>
            {{ form.born_location }}
            <span class="error">{{ form.errors.born_location }}</span>
        </div>
        <div class="form-group mb-3">
            <label for="id_description">Description:</label>
            {{ form.description }}
            <span class="error">{{ form.errors.description }}</span>
        </div>
        <div class="buttonForm">
            <button type="submit" class="btn btn-primary">Submit</button>
            <button type="reset" class="btn btn-secondary">Reset</button>
        </div>
    </form>
</div>
{% endblock %}

mysite/quotes/templates/quotes/add_quote.html
{% extends "quotes/base.html" %}

{% block content %}
<div class="container">
    <h2 class="titleForm">Add Quote:</h2>
    <br>
    <form class="col-sm-8" method="POST" action="{% url 'quotes:add_quote' %}">
        {% csrf_token %}
        <div class="form-group mb-3">
            <label>Author:</label>
            {{form.author}}
            <span>{{ form.errors.author }}</span>
        </div>
        <div class="form-group mb-3">
            <label>Quote:</label>
            {{ form.quote }}
            <span>{{ form.errors.quote }}</span>
        </div>
        <div class="form-group mb-3">
            <label>Tags:</label>
            {{ form.tags }}
            <span>{{ form.errors.tags }}</span>
        </div>
        <br>
        <div class="buttonForm">
            <button type="submit" class="btn btn-primary btn">Submit</button>
            <button type="reset" class="btn btn-secondary btn">Reset</button>
        </div>
    </form>
</div>
{% endblock %}

mysite/quotes/templates/quotes/author.html
{% extends "app_quotes/base.html" %}
{% block content %}
<div class="author-details">
    <h3 class="author-title">{{author.fullname}}</h3>
    <p>
        <strong>Born:</strong> <span class="author-born-date">{{author.born_date}}</span>
        <span class="author-born-location">{{author.born_location}}</span>
    </p>
    <p><strong>Description:</strong></p>
    <div class="author-description">
        {{author.description}}
    </div>
</div>
{% endblock %}

mysite/quotes/templates/quotes/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">

    <title>Quotes to scrape</title>
</head>
<body>
<div class="container">
        <div class="row header-box pt-3" >
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
            <div class="col-md-4">
                <p>

                    {% if user.is_authenticated %}
                    <a href="/users/logout" class="btn btn-light">Logout</a>
                    <a href="{% url 'quotes:add_quote' %}" class="btn btn-light">Add Quote</a>
                    <a href="{% url 'quotes:add_author' %}" class="btn btn-light">Add Author</a>
                    {% else %}
                    <a href="/users/login" class="btn btn-light">Login</a>
                    <a href="/users/signin" class="btn btn-light">Signin</a>
                    {% endif %}

                </p>
            </div>
        </div>


    {% block content %} {% endblock %}

</div>
</body>
</html>

mysite/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}
<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}

    <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop="text"> {{quote.quote}} </span>
        <span>by <small class="author" itemprop="author">{{quote.author|author}}</small>
        <a href="/author/{{quote.author}}">(about)</a>
        </span>
        <div class="tags">
            Tags:
            {% for tag in quote.tags %}
            <a class="tag" href="/tag/{{tag}}">{{tag}}</a>
            {% endfor %}

        </div>
    </div>
        {% endfor %}
        <nav>
            <ul class="pager">

                <li class="previous">
                    <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                       href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {%else%} # {% endif %}">
                        <span aria-hidden="true">←</span> Previous</a>
                </li>


                <li class="next">
                    <a class="{% if not quotes.has_next %} disabled {% endif %}"
                            href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {%else%} # {% endif %}">
                        Next <span aria-hidden="true">→</span></a>
                </li>

            </ul>
        </nav>
    </div>

</div>

{% endblock %}

mysite/users/templates/users/login.html
{% extends 'quotes/base.html' %}

{% block content %}

<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h2 class="mb-4">Log In</h2>

      {% if form.errors %}
        <div class="alert alert-danger" role="alert">
          {{ form.non_field_errors }}
        </div>
      {% endif %}

      {% if messages %}
        <div>
          {% for message in messages %}
            <div {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %} role="alert">
              {{ message }}
            </div>
          {% endfor %}
        </div>
      {% endif %}

      <form method="post">
        {% csrf_token %}

        <div class="mb-3">
          <label for="username" class="form-label">Username:</label>
          {{ form.username }}
          <span class="text-danger">{{ form.errors.username }}</span>
        </div>
        <div class="mb-3">
          <label for="password" class="form-label">Password:</label>
          {{ form.password }}
          <span class="text-danger">{{ form.errors.password }}</span>
        </div>
         <div class="small text-center">
            <a href="{% url 'users:password_reset' %}" class="text-center"><i>Forgot Password?</i></a>
        </div>
        <div class="d-grid gap-2 col-6 mx-auto">
          <button type="submit" class="btn btn-primary btn-sm">Submit</button>
          <button type="reset" class="btn btn-secondary btn-sm">Reset</button>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}

mysite/users/templates/users/logout.html
{% extends 'quotes/base.html' %}

{% block content %}

<h1> Have a nice day! </h1>

{% endblock %}

mysite/users/templates/users/password_reset.html
{% extends "quotes/base.html" %}

{% block content %}

<h2>Password reset</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Request password reset</button>
</form>

{% endblock %}

mysite/users/templates/users/password_reset_complete.html
{% extends "quotes/base.html" %}

{% block content %}

    <h2>Password reset complete!</h2>

{% endblock %}

mysite/users/templates/users/password_reset_confirm.html
{% extends "quotes/base.html" %}

{% block content %}

<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save new password</button>
</form>

{% endblock %}

mysite/users/templates/users/password_reset_done.html
{% extends "quotes/base.html" %}

{% block content %}

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>

{% endblock %}

mysite/users/templates/users/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
        Reset password
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

mysite/users/templates/users/signin.html
{% extends 'quotes/base.html' %}

{% block content %}

<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h2 class="mb-4">Sign In</h2>

      {% if form.errors %}
        <div class="alert alert-danger" role="alert">
          {{ form.non_field_errors }}
        </div>
      {% endif %}

      <form method="post">
        {% csrf_token %}

        <div class="mb-3">
          <label for="username" class="form-label">Username:</label>
          {{ form.username }}
          <span class="text-danger">{{ form.errors.username }}</span>
        </div>
        <div class="mb-3">
          <label for="email" class="form-label">Email:</label>
          {{ form.email }}
          <span class="text-danger">{{ form.errors.email }}</span>
        </div>
        <div class="mb-3">
          <label for="password1" class="form-label">Password:</label>
          {{ form.password1 }}
          <span class="text-danger">{{ form.errors.password1 }}</span>
        </div>
        <div class="mb-3">
          <label for="password2" class="form-label">Confirm Password:</label>
          {{ form.password2 }}
          <span class="text-danger">{{ form.errors.password2 }}</span>
        </div>

        <div class="d-grid gap-2 col-6 mx-auto">
          <button type="submit" class="btn btn-primary btn-sm">Submit</button>
          <button type="reset" class="btn btn-secondary btn-sm">Reset</button>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}